### ISSUE TITLE
A roadmap for 0.3.0

### ISSUE THREAD

**Issue by dcao** [elba/elba#41]
Instead of scrapping what we have for an Idris version, we can continue iterating on the current Rust-based version of elba, since there are still some places we can improve things:

  - [x] The interaction with git repositories and lockfiles is a little dicey at the moment, and some more concrete behavior should be implemented
    - Already solved
  - [X] Blodwen/Idris 2 should be supported
    - [X] With the addition of virtual packages and build scripts, we can now create a package that represents the compiler
    - [X] The `compile*` functions will handle moving output binary files to the right place
    - [x] The `*Invocation` structs will deal with differences in CLI structure between Idris 1 and 2.
  - [X] We should try to make the build system less fragile
    - [X] For now, we won't try to sanitize build options
    - [x] elba now has an explicit `package.exclude` manifest key for specifying if an item shouldn't get moved into a lib dir
  - [ ] Revamped docs that cover all features without restating info multiple times
    - [x] Improved IDE integration (#43)
  - [X] Refined registries (#37)
    - [X] `backend` -> `registry`
  - [X] Scripts have been implemented; tasks can come later

**Comment by nikolaipaul** [comment]
Is there any plan for a searchable web repository?

**Comment by dcao** [comment]
@nikolaipaul Watch the [elba/website](https://github.com/elba/website) repository; there's currently a full elba website being built.
